# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessagePlayer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessagePlayer.proto',
  package='Message',
  serialized_pb='\n\x13MessagePlayer.proto\x12\x07Message\";\n\x0bPlayerLogin\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0b\n\x03pid\x18\x02 \x01(\x03\x12\x12\n\ntemplateid\x18\x03 \x01(\x05\"\x1b\n\x0cPlayerLogout\x12\x0b\n\x03pid\x18\x01 \x01(\x03\"|\n\x0c\x43reatePlayer\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0e\n\x06server\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0croletemplate\x18\x04 \x01(\x05\x12\x0b\n\x03pid\x18\x05 \x01(\x03\x12\r\n\x05stunt\x18\x06 \x01(\x05\x12\x0f\n\x07quality\x18\x07 \x01(\x05\"\x1b\n\x0c\x44\x65letePlayer\x12\x0b\n\x03pid\x18\x01 \x01(\x03\":\n\x10\x43heckNameRequest\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0b\n\x03pid\x18\x02 \x01(\x03\x12\x0c\n\x04name\x18\x03 \x01(\t\"=\n\x11\x43heckNameResponse\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0b\n\x03pid\x18\x02 \x01(\x03\x12\x0e\n\x06result\x18\x03 \x01(\x08\"*\n\x0bPlayerCount\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0e\n\x06player\x18\x02 \x03(\x03\"\x8d\x01\n\x0ePlayerAttrSync\x12\x0b\n\x03pid\x18\x01 \x01(\x03\x12*\n\x04\x61ttr\x18\x02 \x03(\x0b\x32\x1c.Message.PlayerAttrSync.Attr\x1a\x42\n\x04\x41ttr\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05val32\x18\x02 \x01(\x05\x12\r\n\x05val64\x18\x03 \x01(\x03\x12\x0e\n\x06valstr\x18\x04 \x01(\t\"\x1d\n\x0ePlayerLoadOver\x12\x0b\n\x03pid\x18\x01 \x01(\x03\"<\n\x14ObservePlayerRequest\x12\x10\n\x08playerid\x18\x01 \x01(\x03\x12\x12\n\nplayername\x18\x02 \x01(\t')




_PLAYERLOGIN = _descriptor.Descriptor(
  name='PlayerLogin',
  full_name='Message.PlayerLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.PlayerLogin.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.PlayerLogin.pid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='templateid', full_name='Message.PlayerLogin.templateid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=91,
)


_PLAYERLOGOUT = _descriptor.Descriptor(
  name='PlayerLogout',
  full_name='Message.PlayerLogout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.PlayerLogout.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=93,
  serialized_end=120,
)


_CREATEPLAYER = _descriptor.Descriptor(
  name='CreatePlayer',
  full_name='Message.CreatePlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.CreatePlayer.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server', full_name='Message.CreatePlayer.server', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Message.CreatePlayer.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roletemplate', full_name='Message.CreatePlayer.roletemplate', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.CreatePlayer.pid', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stunt', full_name='Message.CreatePlayer.stunt', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quality', full_name='Message.CreatePlayer.quality', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=122,
  serialized_end=246,
)


_DELETEPLAYER = _descriptor.Descriptor(
  name='DeletePlayer',
  full_name='Message.DeletePlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.DeletePlayer.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=248,
  serialized_end=275,
)


_CHECKNAMEREQUEST = _descriptor.Descriptor(
  name='CheckNameRequest',
  full_name='Message.CheckNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.CheckNameRequest.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.CheckNameRequest.pid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Message.CheckNameRequest.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=277,
  serialized_end=335,
)


_CHECKNAMERESPONSE = _descriptor.Descriptor(
  name='CheckNameResponse',
  full_name='Message.CheckNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.CheckNameResponse.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.CheckNameResponse.pid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='Message.CheckNameResponse.result', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=337,
  serialized_end=398,
)


_PLAYERCOUNT = _descriptor.Descriptor(
  name='PlayerCount',
  full_name='Message.PlayerCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.PlayerCount.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player', full_name='Message.PlayerCount.player', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=400,
  serialized_end=442,
)


_PLAYERATTRSYNC_ATTR = _descriptor.Descriptor(
  name='Attr',
  full_name='Message.PlayerAttrSync.Attr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Message.PlayerAttrSync.Attr.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val32', full_name='Message.PlayerAttrSync.Attr.val32', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val64', full_name='Message.PlayerAttrSync.Attr.val64', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valstr', full_name='Message.PlayerAttrSync.Attr.valstr', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=520,
  serialized_end=586,
)

_PLAYERATTRSYNC = _descriptor.Descriptor(
  name='PlayerAttrSync',
  full_name='Message.PlayerAttrSync',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.PlayerAttrSync.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='Message.PlayerAttrSync.attr', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PLAYERATTRSYNC_ATTR, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=445,
  serialized_end=586,
)


_PLAYERLOADOVER = _descriptor.Descriptor(
  name='PlayerLoadOver',
  full_name='Message.PlayerLoadOver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.PlayerLoadOver.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=588,
  serialized_end=617,
)


_OBSERVEPLAYERREQUEST = _descriptor.Descriptor(
  name='ObservePlayerRequest',
  full_name='Message.ObservePlayerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerid', full_name='Message.ObservePlayerRequest.playerid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playername', full_name='Message.ObservePlayerRequest.playername', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=619,
  serialized_end=679,
)

_PLAYERATTRSYNC_ATTR.containing_type = _PLAYERATTRSYNC;
_PLAYERATTRSYNC.fields_by_name['attr'].message_type = _PLAYERATTRSYNC_ATTR
DESCRIPTOR.message_types_by_name['PlayerLogin'] = _PLAYERLOGIN
DESCRIPTOR.message_types_by_name['PlayerLogout'] = _PLAYERLOGOUT
DESCRIPTOR.message_types_by_name['CreatePlayer'] = _CREATEPLAYER
DESCRIPTOR.message_types_by_name['DeletePlayer'] = _DELETEPLAYER
DESCRIPTOR.message_types_by_name['CheckNameRequest'] = _CHECKNAMEREQUEST
DESCRIPTOR.message_types_by_name['CheckNameResponse'] = _CHECKNAMERESPONSE
DESCRIPTOR.message_types_by_name['PlayerCount'] = _PLAYERCOUNT
DESCRIPTOR.message_types_by_name['PlayerAttrSync'] = _PLAYERATTRSYNC
DESCRIPTOR.message_types_by_name['PlayerLoadOver'] = _PLAYERLOADOVER
DESCRIPTOR.message_types_by_name['ObservePlayerRequest'] = _OBSERVEPLAYERREQUEST

class PlayerLogin(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERLOGIN

  # @@protoc_insertion_point(class_scope:Message.PlayerLogin)

class PlayerLogout(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERLOGOUT

  # @@protoc_insertion_point(class_scope:Message.PlayerLogout)

class CreatePlayer(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEPLAYER

  # @@protoc_insertion_point(class_scope:Message.CreatePlayer)

class DeletePlayer(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEPLAYER

  # @@protoc_insertion_point(class_scope:Message.DeletePlayer)

class CheckNameRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKNAMEREQUEST

  # @@protoc_insertion_point(class_scope:Message.CheckNameRequest)

class CheckNameResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKNAMERESPONSE

  # @@protoc_insertion_point(class_scope:Message.CheckNameResponse)

class PlayerCount(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERCOUNT

  # @@protoc_insertion_point(class_scope:Message.PlayerCount)

class PlayerAttrSync(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Attr(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PLAYERATTRSYNC_ATTR

    # @@protoc_insertion_point(class_scope:Message.PlayerAttrSync.Attr)
  DESCRIPTOR = _PLAYERATTRSYNC

  # @@protoc_insertion_point(class_scope:Message.PlayerAttrSync)

class PlayerLoadOver(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERLOADOVER

  # @@protoc_insertion_point(class_scope:Message.PlayerLoadOver)

class ObservePlayerRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OBSERVEPLAYERREQUEST

  # @@protoc_insertion_point(class_scope:Message.ObservePlayerRequest)


# @@protoc_insertion_point(module_scope)
