# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageDebug.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageDebug.proto',
  package='Message',
  serialized_pb='\n\x12MessageDebug.proto\x12\x07Message\",\n\x0c\x44\x65\x62ugRequest\x12\x0f\n\x07strings\x18\x01 \x03(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x03\":\n\x0eNetTestRequest\x12\n\n\x02no\x18\x01 \x02(\x05\x12\r\n\x05idata\x18\x02 \x03(\x05\x12\r\n\x05sdata\x18\x03 \x01(\t')




_DEBUGREQUEST = _descriptor.Descriptor(
  name='DebugRequest',
  full_name='Message.DebugRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strings', full_name='Message.DebugRequest.strings', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.DebugRequest.pid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=75,
)


_NETTESTREQUEST = _descriptor.Descriptor(
  name='NetTestRequest',
  full_name='Message.NetTestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='no', full_name='Message.NetTestRequest.no', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idata', full_name='Message.NetTestRequest.idata', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sdata', full_name='Message.NetTestRequest.sdata', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=77,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['DebugRequest'] = _DEBUGREQUEST
DESCRIPTOR.message_types_by_name['NetTestRequest'] = _NETTESTREQUEST

class DebugRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEBUGREQUEST

  # @@protoc_insertion_point(class_scope:Message.DebugRequest)

class NetTestRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NETTESTREQUEST

  # @@protoc_insertion_point(class_scope:Message.NetTestRequest)


# @@protoc_insertion_point(module_scope)
